; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = ESP32 RZ568M ProperDrive Clock
default_envs = esp32-rz568

[env:esp32-rz568]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_flags = -Os
;board_build.partitions = default.csv
board_build.partitions = default_8MB.csv
;board_build.partitions = default_16MB.csv
upload_port = /dev/ttyUSB*
monitor_port = /dev/ttyUSB*
monitor_speed = 115200
;board_build.f_cpu = 160000000L
lib_deps = 
	paulstoffregen/Time@^1.6.1
	ottowinter/ESPAsyncWebServer-esphome@^3.0.0
	bblanchon/ArduinoJson@5.13.4
	adafruit/Adafruit GFX Library@^1.11.3
	adafruit/Adafruit SSD1306@^2.5.7
	adafruit/Adafruit BusIO@^1.13.2
	ayushsharma82/AsyncElegantOTA@^2.2.7
	makuna/NeoPixelBus@^2.7.0
	adafruit/Adafruit SH110X@^2.1.8
	madhephaestus/ESP32Encoder@^0.9.2
